// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://diibxulclbjsqenjshrb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpaWJ4dWxjbGJqc3FlbmpzaHJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcyMDgwMzEsImV4cCI6MjA1Mjc4NDAzMX0.YiUkaWaUtfCHy7DL7i1fo8pPnEHG6Sa89rv3tMQRcDE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);